version: '3.9' 
services:
  123strm:
    privileged: true
    container_name: 123strm
    image: dinding1/123strm:v3.0
    network_mode: host
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - TG_TOKEN=5869372349:AAEYktPRZlsNAf-PkCRGcyaxb65vh4f5unQ
      - BASE_URL=http://172.17.0.1:8123
    volumes:
      - ./cache:/app/strm_output

