name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'VERSION'  # 仅当 VERSION 文件被修改时触发

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read Version
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d '[:space:]')  # 读取 VERSION 文件内容
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image (Multi-Arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64  # 多架构支持
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/123strm:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/123strm:${{ steps.version.outputs.version }}



